### ISSUE TITLE
Is timing_object supposed to be there?

### ISSUE THREAD

**Issue by ethhics** [beerjson/beerjson#179]
In the root object `beerjson`, there is a `TimingType` member called `timing_object`. I can't figure out why it's there, though, and wonder if it was added by mistake.

The only time that time should play a role is for `*ProcedureType`s, `*StepType`s, and `*AdditionType`s, but all of those have time objects featured in them.

Am I missing a reason for `timing_object` to be part of the root object?

**Comment by pricelessbrewing** [comment]
It's been awhile since I made it, and was definitely still learning, but I believe it was necessary at the time in order for the build to pass CI and/or for it to be added to the documentation properly but as long as the code's still valid and the description is still in place for the relevant documentation in fermentables/hops/misc/cultures then I'm fine with moving it to another place.

**Comment by krutilin** [comment]
Removed TimingType from root object, see pr #180
