### ISSUE TITLE
Equipment profile

### ISSUE THREAD

**Issue by krutilin** [beerjson/beerjson#19]
There is no any description of the Equipment profile in the beerxml 2.0 and in beerjson too.

**Comment by jdominiczak** [comment]
I think this is a necessary optional data structure.  While I understand that everyone's brewing system is personal to them and often different, having this is quite informative when archiving one's personal brewing.

**Comment by m00nh34d** [comment]
It would be good to define to make equipment profiles portable between applications. It's a complex data structure though, lots of variables here.

Some of the data from an equipment profile is needed for the recipe, but not all of it, would this continue to live in the recipe, or would this be replaced by a link to the equipment profile object? I personally believe they should be decoupled, as linking the equipment profile to a recipe, makes the recipe less portable (or maybe not, depending on the implementation), but I can certainly see issues importing a recipe with a linked equipment profile and then needing to change that equipment profile to match your set up for the recipe to work (as opposed to just changing the efficiency and volumes in the recipe).

**Comment by krutilin** [comment]
Well, the recipe is description how to brew portion of beer or whatever. But it should not contain equipment description. Because each brewer has it's own equipment. And there should be methods to scale to concrete equipment in software which uses beerjson as the data structure. Also, there should be methods to calculate efficiency, water, and other losses according to current equipment.

I'll try to create some draft data structure for equipment description, according to beerxml 1.0 and together we will extend it by adding reasonable fields.

**Comment by pricelessbrewing** [comment]
As long as the process is described fully, then it doesn't matter what the equipment is. I haven't set the 2.0 standard to memory yet, but OTOH I don't think the last standard included a complete set that described all wort volumes and equipment losses. 

This is crucial to recipe scaling for different equipment, and is the source for different people getting different beer out of the same recipe. Someone with mashtun or kettle losses will get different intensity of grain flavors via dulition. Similarly, someone with kettle losses will need to use more hops due to dilution, a complete set of efficiency numbers should also be added with brewhouse as required and the rest as optional.

**Comment by m00nh34d** [comment]
At minimum we need the attributes from an equipment profile, such as the various losses and efficiency numbers, in order to make the recipe complete.

That said, in order to make this format useful for the applications, we will need to include a link an instance of full equipment object in use.

For example, when building a recipe, you'll want to link it to an equipment profile in your application, so that will need to be saved in this file format. You'll want an instance of this equipment so you can change it for an individual recipe.

This does have some benefits for homebrewing equipment, especially with the popularity of robo brew systems, which share very similar equipment profiles.

**Comment by m00nh34d** [comment]
Also, on the equipment profiles, it would be good to include grain absorption. Right now, in Beersmith for example, this is a global application setting, when in reality it varies depending on your equipment and how you use it.

**Comment by pricelessbrewing** [comment]
If absorption rates are added to the schema, then we'll need to make sure we can either set a ratio of two unit types, or define a new unit type as Volume / Mass.
