### ISSUE TITLE
BeerJSON thread (s) social media 

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#48]
I had opened a thread over the MTF, which is an awesome resource for sour/funky beers, and has a lot of pro brewers as well. The topic was basically "what do you want?", since they're such an isolated group in regards to software and trying to get a sour recipe to fit the beerxml standard is almost impossible, I wanted their feedback especially. Most of the issues I've opened recently have been from this thread. 

https://www.facebook.com/groups/MilkTheFunk/permalink/1982242271803977/

I will additionally be posting a thread at r/homebrewing and r/brewery in the near future to gauge interest, and get more feedback. I'll add links to those as they arise.

**Comment by krutilin** [comment]
Great, It is vital for such kind of project to be in touch with brewers and developers. I also sent the request to join their group.

Btw. We got some starting of feedback and ideas from this post:
https://www.reddit.com/r/Homebrewing/comments/7ej733/bregrammers_lets_work_on_beerjson_beerxml_2/
three months ago.

I think we will figure out some lifecycle for media threads on the project planning board (need to think how to make it better). Because issues list is not a good place for that.

**Comment by krutilin** [comment]
I created the column in the beerjson git project with links. Will close this issue for now.
