### ISSUE TITLE
Versioning. Is it possible to apply semantic versioning to the schema?

### ISSUE THREAD

**Issue by krutilin** [beerjson/beerjson#53]
https://semver.org/

**Comment by pricelessbrewing** [comment]
If I understand this correctly, current version on readme should change to 0.X.Y and the 1.0 branch can be deleted until a stable production ready branch is declared.

**Comment by krutilin** [comment]
Here is a good (but old 2014) description of the schema versioning procedure:
https://snowplowanalytics.com/blog/2014/05/13/introducing-schemaver-for-semantic-versioning-of-schemas/

**Comment by pricelessbrewing** [comment]
Since @krutilin mentioned it in #98. 

IMO I don't think we should start applying semantic versioning until a production ready version (1.0) release, per this issue.

Which I think necessitates addressing #89, #77, #31, #51 and #83. 

#31 This is easy, and I can submit a PR for it soon.

#83 Is needed for whirlpooling hop additions, and non boiling pasteurization steps. 

#51 Is needed for packaging keg, and culture additions, as well as increasing support for pro breweries for keg tracking. 

Additionally, I think we need to go through and add some descriptions for anything that needs it, we're largely missing descriptions, and update the tests/real to include more examples for some of the less straightforward aspects of the schema.

**Comment by superroma** [comment]
Just a note - shouldn't we version it 2.0 when it is ready? It is based on BeerXML 2 after all.

**Comment by superroma** [comment]
Project tab can help visualize this: https://github.com/beerjson/beerjson/projects/1

**Comment by pricelessbrewing** [comment]
> Just a note - shouldn't we version it 2.0 when it is ready? It is based on BeerXML 2 after all.

If this were the same project, then I would say yes. But since this has become more of a replacement of BeerXML, and is in fact a separate project I would say 1.0 should be the production ready release version. But I'm the new guy, so I could be wrong.

**Comment by pricelessbrewing** [comment]
@beerjson/beerjson-admin Can we change the readme description to whatever version we're going to use, IMO it should be a 0.X version until we have a release ready for testing and public use from my understanding of SemVer, since this is a separate project from BeerXML. Then we can close this I think?

**Comment by pricelessbrewing** [comment]
@krutilin @superroma What's the verdict? Are we going with version 0.1 right now and treating this as a seperate project from the current BeerXML, or starting at 2.0? 

I'd like to submit a PR to close this issue.

**Comment by PierreSmits** [comment]
I would say that the versioning of beerjson should be independent of what BeerXML uses. There is always the possibility to reference the applicable BeerXML version.

**Comment by pricelessbrewing** [comment]
I agree with @PierreSmits, we are currently something like version 0.8.0 or similar IMO. 0.9.0 could be documentation changes are completed, then do a cleanup review before launching 1.0 and going forward with #104 

@krutilin @superroma Can we get a vote from you two?
