### ISSUE TITLE
Lets focus on Recipe Exchange scenario

### ISSUE THREAD

**Issue by superroma** [beerjson/beerjson#58]
Hi working group,

First, thank you for your efforts, I'm glad the real work has started here!

Reading latest discussions, I can see more and more a discussion about what internal data every application needs. And this leads to question - should we really standardize internal data structures of our apps? I believe no, the purpose of BeerJSON standard would be a data interchange between apps.

What data we need to interchange? What scenarios do we have?

I see these scenarios so far (most important first):
* **Recipe Exchange**. Be able to share and use recipes created in any app out there.
*  **Ingredient Exchange**. Download ingredient definition(s) from somewhere.
* **Migrate to another app**. Be able to export/import every piece of data you have in the app (like equipment, brew logs, inventory, measured values).

Recipe and ingredient exchange scenarios looks much more important to me. So I suggest we focus on Recipe Exchange first. Which means instead of thinking "what data do I want to have in my app?", think "what data do I need from the stranger's app to make recipe complete in my app?".

What do you think?

**Comment by rmsrosa** [comment]
At first I was repelling the third option, but at some point I realized it would be interesting to have it as well, in case we want to change from one app to another, as you said, or to archive more details of the brewing process without having to write everything in the notes.

But I agree that the first two points are more important and I think we need to focus on these two and finish version 1 of the schema.

**Comment by pricelessbrewing** [comment]
>Standardize internal data structures. 

Don't really care how the data is handled internally, but IMO if enough of the "big guys" as far as recipe software goes, are supporting a feature, then I think it would be beneficial to standardize that feature so that the recipes are cross compatible as far as exporting a recipe file. Especially if the feature is something that is commonplace and should be included in the schema. Otherwise it ends up as a "optional" property, and software A might structure it differently than software B and C which means any recipe used isn't supported the same and won't be cross compatible, which was the entire purpose of beerxml. 

Agreed on importance of Recipe / Ingredient / migration.

Regarding ingredient database, I'd ask @mikfire and @rocketman768 if we could use the ingredient database of brewtarget. Although I would suggest using something else for the yeast, as I believe their yeast structure uses a single value for the apparent attenuation instead of the more common range that yeast labs and other software uses. Additionally there is the brewerwall repo which might be of use, doesn't seem like it's actively maintained, but it's all in json format already! https://github.com/griffithben/brewerwall

**Comment by mikfire** [comment]
I am 100% ok with you using brewtarget's db as a seed, but I really don't think I have much claim to the data. I really just caused problems in the display layers. @rocketman768 has the final say on it.

**Comment by griffithben** [comment]
Same with Brewerwall.  I think I have everything setup in separate repo's, but if you find something missing just let me know.

**Comment by pricelessbrewing** [comment]
Closing
