### ISSUE TITLE
There are no tests for the water.json

### ISSUE THREAD

**Issue by krutilin** [beerjson/beerjson#68]
Need to cover this part too.

**Comment by pricelessbrewing** [comment]
There is both a generic test, profile.json, and a real test SampleWaterProfile.json.

Is there something else you had in mind? I know water additions are currently missing from the water profile, as I believe they're being treated using the misc ingredients type of "water agent". 

When we get to documentation descriptions, we'll need to determine if the water profiles being stored in the recipe is that of the untreated water, or that of the treated water, and if we're going with treated water then I think we need to move water agents to the water.json file, and list both the untreated and treated water since every software package has different models and formulas for estimating resultant profiles and mash/sparge pH . 

Question @beerjson/beerjson-wg  are we going to list things like total sulfate, and chloride (and SO4 / CL ratio)? Pretty useful metric IMO. 

I think the generic water test profile.json needs to be renamed to water.json though.

**Comment by krutilin** [comment]
Seems description is not clear on this issue. My fall. 
I can't find tests for the "water_additions" in "ingredients" in the recipe.json schema.

Also renaming profile.json to water.json is a good idea.

**Comment by pricelessbrewing** [comment]
I think this needs to be a discussion before merging the PR #72. 

We'll need to assign units to the minerals, is it's mg / L, ppm, ppb, g/mol, mEq/l, German Hardness dH, french hardness TH? Is it measured directly or is it expressed as alkalinity of "ppm as CaCO3"? 

Moreover, how will different water sources be handled? I know some brewers use RO + minerals for mash additions, then switch to a different water treatment for sparging water or topping off. Should the additions then be listed as a subset of the mash step infusion object, and/or top off volumes? 

If not, then does the water_additions object will need a volume property and a _step property referring to where it is used?

**Comment by krutilin** [comment]
Sure.

> We'll need to assign units to the minerals, is it's mg / L, ppm, ppb, g/mol, mEq/l, German Hardness dH, french hardness TH? Is it measured directly or is it expressed as alkalinity of "ppm as CaCO3"?

It depends on the schema in the water.json and how deep we will describe water.

> Moreover, how will different water sources be handled? I know some brewers use RO + minerals for mash additions, then switch to a different water treatment for sparging water or topping off. Should the additions then be listed as a subset of the mash step infusion object, and/or top off volumes?

Well, if we check BJCP styles information we will see that water descriptions are like:
"Minerally water with high levels of sulfates, carbonates and chlorides" or "Soft water with low sulfate and carbonate content". So I am not sure about the super detailed description of water, at least of the first steps.

> If not, then does the water_additions object will need a volume property and a _step property referring to where it is used?

We have "amount" property but it is not required. As about _step property, I don't know. I asked some brewers who prepare water and some of them use additional tools for water calculations like http://www.ezwatercalculator.com/ and prepare all water at once without dividing it into the steps.

**Comment by pricelessbrewing** [comment]
https://sites.google.com/site/brunwater/ I'd say is the gold standard for water treatment, as well as the _Water: A Comprehensive Guide for Brewers_ by Colin Kaminski and John Palmer, mentioned in section 6.3.

Acidifying your sparge water is often a necessary step to avoiding tanning extraction, due to the increased pH in the sparge run off as much of the malts buffering capacity has already been spent from the mash. We don't really have a good way of support sparge processes' in the schema, which IMO is worthy of a separate issue. 

I suppose this is less of an issue for water profile, except for pH property, as much as it is for misc ingredient additions needing to support sparge additions.

**Comment by pricelessbrewing** [comment]
On the topic of different water profiles throughout the process, I see three options:

1) At any step in the process where water is added, we specify the water profile and amount, in the infusion object. Basically, we treat any water profile addition as if it were an ingredient addition.

2) For any water profile used in a brew, we specify the amount used and the step in which it was used, in the water profile object. This seems clunky. 

3) We ignore it. _Most_ of the time it will be 1 water profile being used throughout the entire beer, with the exception of RO or distilled water may be used at a few separate steps to _cut_ the base water profile so to speak, or that some water additive like lactic acid or similar may be used at a separate step which is already supported.  

Personally I would like to see 1) being supported, as it makes sense according to any other ingredient addition, and would fit into the existing schema easily.

**Comment by krutilin** [comment]
Well, water_additions in our schema is an array of the water types. And we could specify amount and water params there. 
But I suppose that in current realization we describe "waters" to achieve one "water" for this beer recipe. And it is closer to 3. Water profile for the entire beer. Also, I think that it is ok for most brewers. 

(will close this issue, because water tests added by @pricelessbrewing , as about binding water to steps, it is another issue.)
