### ISSUE TITLE
FermentableType

### ISSUE THREAD

**Issue by neyc** [beerjson/beerjson#88]
FermentableType:ibu_gal_per_lb 
	I'm not an extract brewer. Anyway this should apply also to extracts based on liter_per kg. 
	So it would need an unit-value object in order to be consistent with other data in beerJson.
	BeerXml states: For hopped extracts only - an estimate of the number of IBUs per pound of extract in a gallon of water.
	So why not name that property 'hopped_extract_ibu'. Would be more human readable.
	
FermentableAdditionType:yield
	is this the same yield as in FermentableType:yield_dry_basis?
	
The RecipeType.fermentable_bill allows items of FermentableAdditionType. Why not of FermentableType? Shouldn't it be FermentableType? 
How would you transform an BeerXml which requires 'fine_grind'?

I would use FermentableBase for all BeerXml tags which are required plus objects we declare as required. Other tags would be in FermentableType and FermentableAdditionType should be removed.

diastatic_power: can be in Windisch-Kolbach units (degrees °WK) or °Lintner 
see https://en.wikipedia.org/wiki/Degree_Lintner. Now it just accepts a number.

The FermentableBase.group enum does not have 'Rye'. See 
https://www.weyermann.de/eng/gelbe_Seiten_en.asp?snr=1&idkat=1018&umenue=yes&idmenue=37&sprache=2

**Comment by pricelessbrewing** [comment]
Will do my best to address each point. Some of it is addressed in #85. 

Ibu per gallon can be used for non extract ingredients, although extract is much more common. For example you may add a hopped beer into another beer recipe, or hopped wort, boiled cider etc. 

Agreed on unit-value pair. 

Yield, potential, coarse grind fine grind etc all should be moved to a single object of yield, as described in #85. (Or similar if better alternative is suggested). 

Recipe uses fermentable addition, which is based on the fermentable base. A recipe should only ever list the ingredients used in the recipe. This is consistent with all ingredients. 

Diaststic power, good point. Will need to be added to the measurable units and the property changed to a "one of" or an object that can accept either unit but must not be empty (min item 1). 

>Rye.

I really don't see the benefit of this type of specification. Does rye malt belong in rye, or malt, or both? What about wheat, spelt, oat, corn, rice, buckwheat etc. For consistency, any grain should either fall into malt, or adjunct. If it's flaked, raw unmalted etc, then it's an adjunct by definition.

**Comment by neyc** [comment]
Quote:"Recipe uses fermentable addition, which is based on the fermentable base. A recipe should only ever list the ingredients usd in the recipe".

I guess that is where I disagree. A recipe should describe as specific as possible how to reproduce the beer. The more information I can share the more it likely it is that I can reproduce it. Like a physic or chemical experiment. When the properties of FermentableType are not required you can omit them or share them. So there is no harm done. 

It would share the information  as you said "should only ever list the ingredients used in the recipe". In case I have the information and think they may influence the outcome of the recipe I can add them. In your case I'm stuck. I can't share those details!

Quote:  "This is consistent with all ingredients."
Yes, it is. And in my point of view wrong as well.

Anyway. I apologize. I never worked with GitHub. Have no clue who is doing what in this project and didn't read all the issues already discussed.  All I think is that BeerJson would be the right way to share information. Malters and Hop-providers could share their Json-data with users if the software they use, could incorporate those information. And of course share recipes.

**Comment by pricelessbrewing** [comment]
>malsters and hop brokers

That would be amazing if there was a central ingredient database that ingredient manufacturers/growers could maintain. But afaik it's outside the scope of this project. 

It's still supported through the use of a hop.json file, similar to how the test files are set up. In the event of sharing an ingredient between brewers or developers, you can share a file structured as an ingredient.json file which should be readable by software that supports BeerJSON. 

https://github.com/beerjson/beerjson/blob/master/tests/real/HopRecordWithAllFields.json

**Comment by neyc** [comment]
Where is the difference of sharing a recipe or ingredient information? As I said. A recipe should be as reproducible as possible. 
So that are almost the same data. Some hop-providers share more information than others. Same for malt. Some have information about the Linalool content. Others not. But why should the specification not allow the Linalool content? If it's not there. Fine! If it's there. Ok. Some more bytes. You decide. But it should be in the specifications. So that it would be possible to share it.

**Comment by pricelessbrewing** [comment]
Agreed with all oil content, and all malt spec sheet properties should be supportable IMO. 

A single ingredient will be supported per the ingredient.json file (ie hop.json, fermentable.json), see tests for example. Unless I'm mistaken @beerjson/beerjson-wg @krutilin ? I don't think an array of ingredients is currently within the scope of the project, but it very well could be (ie will beerJSON work to standardize ingredient databases for brewing software as well?)

**Comment by pricelessbrewing** [comment]
Just summarizing the issue, 

Reformat Ibu gal per lb.

to an object like 
"Bitterness:
IBUs (ibu per gallon). Say you want to blend in a hopped cider, hop tea, or 3 gallons of hopped wort or something. unit type: number

Ibu per lb per gal (should be ibus per lb of ingredient per gallon of wort/water it's diluted into).*

Ibu per kg per L.* (metric equivalent of above). 

I don't think anyone will be annoyed that they can't do this in units of Kg/gal or lb per L, or lb per qt or anything like that, which would require it to be IBus per "mass unit type" per "volume unit type" on the fly.

Documentation should note that this is defined in the same manner as malt potential/yield. Ibu per lb of extract diluted into a resultant wort of 1 gallon, so a value of 10 ibus per lb per gallon would necessitate using less than 1 gallon of water, in order to account for the increased volume of adding the extract. This is industry standard for specific gravity, and should apply the same as IBUs. 

Yield/potential types has been taken care of in accordance with industry malster standards. 

Diastatic power needs to be added to measurable units for Windisch-Kolbach units (degrees °WK) or °Lintner. I believe current suggestion by @beerjson/beerjson-wg  is to drop the degrees symbols. 

This should be added to the #16 issue. 

>Rye

Dropping this sort of categorization. It will be in the name and description, otherwise we need to create a long list of acceptable types like sorghum, rice, oats, wheat, spelt, etc etc etc. 



I'm going to go ahead and close this for now, and create a new issue regarding fermentables.json Bitterness restructuring, which should be an easy change.
